spring.application.name=apifilmes
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5432/imdb_api
spring.jpa.hibernate.ddl-auto=update


